---
- name: Copy host resolver
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: Install software-properties-common
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - software-properties-common
    - curl
    - wget
    - nano
  
- name: Install Java
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - openjdk-8-jdk

- name: create user sdn
  user:
    name: sdn
    system: yes

- name: Download and extract ONOS
  unarchive:
    src: http://repo1.maven.org/maven2/org/onosproject/onos-releases/{{ onos-version }}/onos-{{ onos-version }}.tar.gz
    dest: /opt/onos/
    remote_src: yes
    owner: sdn
    group: sdn

- name: Create atomix configuration
  template:
    src: "options.j2"
    dest: "/opt/onos/options"
    owner: sdn
    group: sdn

- name: Create atomix configuration
  template:
    src: "cluster.json.j2"
    dest: "/opt/onos/config/cluster.json"
    owner: sdn
    group: sdn

- name: copy files
  copy:
    remote_src: yes
    src: /opt/onos/init/onos.initd
    dest: /etc/init.d/onos

- name: copy files
  copy:
    remote_src: yes
    src: /opt/onos/init/onos.service
    dest: /etc/systemd/system/

- name: Start ONOS
  systemd:
    name: onos
    state: restarted
    daemon_reload: yes
    enabled: yes