---
- name: Copy host resolver
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: Disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: Install package
  zypper:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - curl
    - wget
    - nano
    - net-tools
    - net-tools-deprecated
    - nmap
    - insserv-compat

- name: Install Java
  zypper:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - java-1_8_0-openjdk

- name: create user sdn
  shell: useradd sdn --system --user-group --create-home

- name: Download and extract ONOS
  unarchive:
    src: http://repo1.maven.org/maven2/org/onosproject/onos-releases/{{ onos_version }}/onos-{{ onos_version }}.tar.gz
    dest: /opt/
    remote_src: yes
    owner: sdn
    group: sdn

- name: stat onos directory
  stat: 
    path: /opt/onos-{{ onos_version }}
  register: onos_stat

- name: Move onos-{{ onos_version }} to onos
  command: mv /opt/onos-{{ onos_version }} /opt/onos
  when: onos_stat.stat.exists

- name: Create onos configuration
  template:
    src: "options.j2"
    dest: "/opt/onos/options"

- name: create onos directory
  file:
    path: /opt/onos/config
    state: directory

- name: Create onos configuration
  template:
    src: "cluster.json.j2"
    dest: "/opt/onos/config/cluster.json"

- name: chown onos directory
  command: chown -R sdn:sdn /opt/onos
  when: onos_stat.stat.exists

- name: copy files
  copy:
    remote_src: yes
    src: /opt/onos/init/onos.initd
    dest: /etc/init.d/onos
    mode: 755

- name: copy files
  copy:
    remote_src: yes
    src: /opt/onos/init/onos.service
    dest: /etc/systemd/system/
    mode: 755

- name: Start ONOS
  systemd:
    name: onos
    state: started
    daemon_reload: yes
    enabled: yes
