---
- name: Copy host resolver
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: Disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: Install package
  zypper:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - curl
    - wget
    - nano
    - net-tools
    - nmap

- name: Install Java
  zypper:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - java-1_8_0-openjdk

- name: create atomix directory
  file:
    path: /opt/atomix
    state: directory

- name: Download and extract atomix
  unarchive:
    src: https://oss.sonatype.org/content/repositories/releases/io/atomix/atomix-dist/{{ atomix_version }}/atomix-dist-{{ atomix_version }}.tar.gz
    dest: /opt/atomix
    remote_src: yes

- name: Create atomix configuration
  template:
    src: "atomix.conf.j2"
    dest: "/opt/atomix/conf/atomix.conf"

- name: Create atomix service files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 644
  with_items:
    - { src: 'atomix.service.j2', dest: '/etc/systemd/system/atomix.service' }

- name: Start atomix
  systemd:
    name: atomix
    state: restarted
    daemon_reload: yes
    enabled: yes